service: "shashikant-coin-switch"

provider:
    name: aws
    runtime: nodejs20.x
    stage: dev
    region: ap-south-1
    apiGateway:
        binaryMediaTypes:
            - "multipart/form-data"
functions:
    app:
        handler: server.handler
        name: shashikant-coin-switch
        events:
            - http:
                  path: /
                  method: ANY
                  cors: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true

plugins:
    - serverless-offline
    # - serverless-event-body-option